name: ICS Generator

on:
  issues:
    types: [labeled]
  schedule:
    - cron: '0 7 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install poetry
          poetry install --sync

      - name: execute py script
        run: python pycon_us_ics/pycon.py
      - run: |
          git config user.name gitevents[bot]
          git config user.email ics@gitevents.org
          git add events.ics
          git commit -m "update calendar file"
          git push